version: '3'

services:
  postgres:
    image: us-east1-docker.pkg.dev/msds-432-assignment6/msdscourse-repo/postgres:14
    container_name: pg14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=master
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - psql
    ports:
      - "5433:5432"

  app:
    image: us-east1-docker.pkg.dev/msds-432-assignment6/msdscourse-repo/msdscourse-app-app:latest
    networks:
      - psql
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  psql:
    driver: bridge