apiVersion: v1
kind: Service
metadata:
  name: msdscourse-app-service
spec:
  selector:
    app: msdscourse-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
